### ISSUE TITLE
Replace `Matrix` with `da.Array` with unknown shapes

### ISSUE THREAD

**Issue by jcrist** [dask/dask-learn#11]
The `Matrix` class was created to support array-like things with unknown shapes, as well as sparse matrices. Since `dask.array` supports these now, we may be able to remove this class.

One issue is that the `Matrix` class does support sparse matrices, while dask array doesn't. In most places we know whether the output of an operation is sparse or dense. The best solution might be to only use `Matrix` for sparse matrices, and use `da.Array` elsewhere.

**Comment by mrocklin** [comment]
Is there a subset of operations for which dask.array would work if its constituent arrays were sparse?  Are there modest changes we could make to the functions we use within dask array graphs that would extend this set of operations?

**Comment by jcrist** [comment]
With the recent rewrite, this is no longer applicable. Closing.
