### ISSUE TITLE
Support lazy evaluation

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-learn#19]
I was trying to see the graph produced by `DaskGridSearchCV.fit`.  My first attempt was to add a `compute=False` keyword.  Looking at the code it's not clear that this is possible.  Is this difficult to support?

**Comment by jcrist** [comment]
Lazy evaluation conflicts with scikit-learn's api, and is tricky to support here in a way that is both intuitive and robust. For some configurations there is also the need to call `get` multiple times, which prevents lazy evaluation.

After calling `fit`, both the graph and the keys are stored on the grid search object as `dask_graph_` and `dask_keys_`. You can also use the `visualize` method on the search object to view the graph:

```python
>>> est.fit(X, y)
>>> est.visualize()
```

**Comment by mrocklin** [comment]
Oh great.  Thanks for the explanation.
