### ISSUE TITLE
The horrible journey to building Elemental with conda on OS X

### ISSUE THREAD

**Issue by ahmadia** [dask/dask-learn#6]
should be significantly easier for Linux, but maybe not.

Problem #1, cmake doesn't like conda's MPI very much, so we'll have to hardcode some MPI variables into the build system. Here's what it looks like on my box:

```
cmake -D CMAKE_INSTALL_PREFIX="~/anaconda3/envs/elemental" \
            -D MPI_C_INCLUDE_PATH:STRING=/Users/qmj240/anaconda3/envs/elemental/include \
            -D MPI_C_LINK_FLAGS:STRING=-L/Users/qmj240/anaconda3/envs/elemental/lib/ \
            -D "MPI_C_LIBRARIES:STRING=-lmpi -lpmpi \
            -L/Users/qmj240/anaconda3/envs/elemental/lib/" ..
```

**Comment by ahmadia** [comment]
changes needed in Elemental are raised as an issue here: https://github.com/elemental/Elemental/issues/149

**Comment by ahmadia** [comment]
`make -j 4` seems to be safe.

**Comment by ahmadia** [comment]
This is a C1 proxy problem.

```
qmj240@f45c899d5ff9 ~/Elemental/build master $ cd source/
qmj240@f45c899d5ff9 ~/Elemental/build/source master $ git clone https://github.com/scibuilder/parmetis.git
```

**Comment by ahmadia** [comment]
Also much needed:

```
-D CMAKE_INSTALL_PREFIX="~/anaconda3/envs/elemental"
```

**Comment by ahmadia** [comment]
Still to do, get a proper conda build recipe for elemental so that we can just build this correctly once and never again. Currently stuck at Python 2 but shouldn't be hard to fix to Python 3 compatibility.

**Comment by jcrist** [comment]
The scope of this project has been reduced to just model parallelism (e.g. grid-search) over small-medium data. It'd still be nice to get this working ,but I'm closing for now, as this is unrelated to this project.

**Comment by mrocklin** [comment]
@ahmadia if you still have an interest in this I've been building a variety of `dask-other` projects recently where other is a distributed system.  I'd be happy to collaborate here if handing off data between systems is still of value to you all and you have someone on the elemental side that is interested in taking this on.
