### ISSUE TITLE
Reassure users of solid parts of this library

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-learn#9]
It seems that the pipeline and gridsearch components of this library are more stable than the "do not use" disclaimer would lead users to believe.  We should find some graceful way of reassuring users that they can uses these components with more confidence than with other parts of the library.

Some options:

1.  Remove "do not use" label entirely.  Possibly 
2.  Create a `dask.learn` submodule in the core dask project and only import the solid parts.  This is what we do for `dask.distributed`
3.  ?

cc @jcrist

**Comment by jcrist** [comment]
I'd still not consider this solid/useful enough to be part of `dask` core. My vote is just to expand the readme to clarify the status a bit better. Good enough?

**Comment by mrocklin** [comment]
Sure
